language: node_js
addons:
  ssh_known_hosts:
  - topdiantop.top
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_de20df944f06_key -iv $encrypted_de20df944f06_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
script:
- CI=false npm run build
after_success:
-ssh -o stricthostkeychecking=no root@www.topdiantop.top "rm -fr /home/travis-test/*"
- scp -r -o stricthostkeychecking=no ./build/* root@www.topdiantop.top:/home/travis-test
