language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_de20df944f06_key -iv $encrypted_de20df944f06_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_succress:
- bash ./travis/deploy.sh