language: node_js

node_js:
  - "node"


# install:
#  - npm install

# script: 
# - CI=false npm run build

after_script:
- scp -o StrictHostKeyChecking=no ./public/* root@www.topdiantop.top:/home/travis-test

