language: node_js
node_js:
- node
after_script:
- scp -o StrictHostKeyChecking=no ./public/* root@www.topdiantop.top:/home/travis-test
before_install:
- openssl aes-256-cbc -K $encrypted_de20df944f06_key -iv $encrypted_de20df944f06_iv
  -in id_rsa.enc -out .travis/id_rsa -d
